# .github/workflows/prerelease.yml
name: prerelease
on:
  push:
    branches: [staging]
permissions:
  contents: write
jobs:
  rc-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm test

      - name: Bump prerelease version (rc)
        id: bump
        shell: bash
        run: |
          curr=$(node -p "require('./package.json').version")
          if [[ "$curr" == *-rc.* ]]; then
            npm version prerelease --preid=rc --no-git-tag-version
          else
            npm version prerelease --preid=rc --no-git-tag-version
          fi
          echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      - name: Commit version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json || true
          git commit -m "chore(release): prerelease bump [skip ci]" || echo "nothing to commit"
          git push || true

      - name: Publish RC to npm (tag: next)
        run: npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.bump.outputs.version }}
          name: v${{ steps.bump.outputs.version }}
          prerelease: true
          generate_release_notes: true
